name: Auto Label Issue
on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Garante permissão no código
    steps:
      - name: Add label
        run: gh issue edit "$NUMBER" --add-label "triage needed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
